#!/usr/bin/env bash

function get_wallpaper_choice() {
  local -r wallpaper_directory="${1}"
  local -r rofi_theme_file="${2}"
  local -a wallpapers
  local wallpaper

  pushd "${wallpaper_directory}" >/dev/null || exit

  # Older bash systems won't have mapfile. Switch to while .. do just in case
  # mapfile -t wallpapers < <(find ~+ -not -path "${wallpaper_directory}" -type f)

  # Omitted one extension because there was a dependancy and I didn't think I'd ever need it.
  # For a list of the extensions supported see here: https://codeberg.org/LGFae/awww
  while IFS= read -r line; do
    wallpapers+=("${line}")
  done < <(find "${wallpaper_directory}" -type f \
    -name "*.jpg" \
    -o -name "*.jpeg" \
    -o -name "*.jpegxl" \
    -o -name "*.webp" \
    -o -name "*.gif" \
    -o -name "*.png" \
    -o -name "*.tiff" \
    -o -name "*.svg" \
    -o -name "*.pnm" \
    -o -name "*.tga" \
    -o -name "*.farbfeld" | sort)

  popd >/dev/null || exit

  if [[ "${#wallpapers[@]}" -eq 0 ]]; then
    return 1
  fi

  for wallpaper in "${wallpapers[@]}"; do
    echo -en "${wallpaper}\0icon\x1f${wallpaper}\n" # thumbnails
  done | rofi -dmenu -show file-browser-extended -theme "${rofi_theme_file}"

  return 0
}

function set_hyprlock() {
  local target_wallpaper="${1}"
  local -r hypr_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"

  # This detemines whether hypridle is running and if it's set to call hyprlock
  if pidof hypridle && grep -q 'lock_cmd.*hyprlock' "${hypr_config_dir}/hypridle.conf"; then
    # Writes the new wallpaper to the lock screen configuration file
    sed -i "s|^\(\s*path\s*=\s*\).*|\1${target_wallpaper}|" "${hypr_config_dir}/hyprlock.conf"
    pkill hyprlock && hyprlock &
  fi
}

function main() {
  # TODO: Parametize or environment variables for next 3 variables.
  local -r wallpaper_dir="${XDG_PICTURES_DIR:-$HOME/Pictures}/Wallpapers"
  local -r rofi_theme_file="${XDG_CONFIG_HOME:-$HOME/.config}/wally/wally.rasi"
  local selection

  if [[ ! -d "${wallpaper_dir}" ]]; then
    return
  fi
  selection=$(get_wallpaper_choice "${wallpaper_dir}" "${rofi_theme_file}")

  if [[ ! -f "${selection}" ]]; then
    return
  fi
  awww img "${selection}" --transition-type center

  set_hyprlock "${selection}"
}

# Only enable these shell behaviours if we're not being sourced
# Approach via: https://stackoverflow.com/a/28776166/8787985
if ! (return 0 2>/dev/null); then
  set -o errexit  # Exit on most errors (see the manual)
  set -o nounset  # Disallow expansion of unset variables
  set -o pipefail # Use last non-zero exit code in a pipeline
fi

main "$@"
